name: .NET MAUI CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: windows-latest

    env:
      Solution_Name: 'SpaceSRM.sln'  # Вкажіть ваше ім'я файлу рішення

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # Вкажіть версію .NET, яку використовує ваш проект

    - name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'  # Використовуйте 'zulu' або 'temurin'
        java-version: '11'

    - name: Install .NET workloads
      run: dotnet workload install maui-android maui-ios maui-maccatalyst

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration Release --no-restore

    - name: Run tests
      run: dotnet test $env:Solution_Name --no-restore --verbosity normal